export const COUNTRY_TO_CONTINENT = {
  Gabon: 'Africa',
  'Aland Islands': 'Europe',
  Malta: 'Europe',
  Mali: 'Africa',
  Czechia: 'Europe',
  Malaysia: 'Asia',
  Tajikistan: 'Asia',
  Ireland: 'Europe',
  'British Indian Ocean Territory (Chagos Archipelago)': 'Asia', // 简化归到 Asia
  Bermuda: 'North America',
  'Russian Federation': 'Europe', // 简化归到 Europe
  'Cook Islands': 'Oceania',
  Ethiopia: 'Africa',
  Fiji: 'Oceania',
  France: 'Europe',
  Germany: 'Europe',
  Lithuania: 'Europe',
  Jamaica: 'North America', // 加勒比海一律归北美
  Mozambique: 'Africa',
  'Saudi Arabia': 'Asia',
  'Holy See (Vatican City State)': 'Europe',
  'Cape Verde': 'Africa',
  'Virgin Islands, U.S.': 'North America',
  Martinique: 'North America',
  Montenegro: 'Europe',
  Samoa: 'Oceania',
  'French Guiana': 'South America',
  Taiwan: 'Asia',
  Micronesia: 'Oceania',
  'Antigua and Barbuda': 'North America',
  'Equatorial Guinea': 'Africa',
  Eritrea: 'Africa',
  Tanzania: 'Africa',
  'Saint Vincent and the Grenadines': 'North America',
  'Trinidad and Tobago': 'North America',
  'Brunei Darussalam': 'Asia',
  'New Caledonia': 'Oceania',
  "Cote d'Ivoire": 'Africa',
  Vanuatu: 'Oceania',
  Curacao: 'North America',
  Mauritius: 'Africa',
  Reunion: 'Africa',
  'United States Minor Outlying Islands': 'Oceania',
  Cambodia: 'Asia',
  Poland: 'Europe',
  'Turks and Caicos Islands': 'North America',
  Portugal: 'Europe',
  Congo: 'Africa',
  Denmark: 'Europe',
  'El Salvador': 'North America',
  Canada: 'North America',
  Pakistan: 'Asia',
  Nigeria: 'Africa',
  'Saint Kitts and Nevis': 'North America',
  Paraguay: 'South America',
  'Saint Martin': 'North America',
  'United Kingdom': 'Europe',
  Aruba: 'North America',
  Bulgaria: 'Europe',
  Hungary: 'Europe',
  'Marshall Islands': 'Oceania',
  'Kyrgyz Republic': 'Asia',
  Rwanda: 'Africa',
  Djibouti: 'Africa',
  'Isle of Man': 'Europe',
  Madagascar: 'Africa',
  Spain: 'Europe',
  Slovakia: 'Europe',
  Iraq: 'Asia',
  Angola: 'Africa',
};
